pipeline {
    agent any
    
    stages {
        stage('Init') {
            steps {
                sh """
                    cd vpc
                    terraform init -reconfigure
                """
            }
        }
    stage('Plan') {
            steps {
                sh """
                    cd vpc
                    terraform plan
                """
            }
        }
    stage('Deploy') {
            when {
                expression { 
                    params.action == 'apply'
                }
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
                // submitter "alice,bob"
                // parameters {
                //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                // }
            }

        }
         stage('Deploy') {
            when {
                expression { 
                    params.action == 'apply'
                }
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
                // submitter "alice,bob"
                // parameters {
                //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                // }
            }
            steps {
                sh """
                    cd vpc
                    terraform apply -auto-approve
                """
            }
        }
         
    }
}
