pipeline {
    agent any
    
    stages {
        stage('Init') {
            steps {
                sh """
                    cd vpc
                    terraform init -reconfigure
                """
            }
        }
     stage('Plan') {
            steps {
                sh """
                    cd vpc
                    terraform plan
                """
            }
        }
    
    }
}
